name: atsign_atmosphere_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+47

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  pedantic: ^1.9.0
  google_fonts: ^2.1.0
  receive_sharing_intent: ^1.4.1
  provider: ^4.3.2+2
  file_picker: ^4.1.3
  video_thumbnail: ^0.2.2
  another_flushbar: ^1.10.18
  webview_flutter: ^2.0.4
  flutter_qr_reader: ^1.0.3
  flutter_local_notifications: ^6.0.0
  rxdart: ^0.24.1
  intl: ^0.17.0
  permission_handler: ^8.1.1
  flutter_slidable: ^0.6.0
  qr_flutter: ^3.2.0
  share: ^2.0.1
  archive: ^3.1.2
  flutter_keychain: ^2.0.1
  open_file: ^3.0.3
  url_launcher: ^6.0.3
  filesystem_picker: ^2.0.0
  package_info: ^0.4.3+4
  hive: ^2.0.4
  hive_flutter: ^1.0.0
# desktop specific libraries
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.4

  at_onboarding_flutter: ^3.0.4
  at_client_mobile: ^3.0.3
  at_contact: ^3.0.1
  at_lookup: ^3.0.3
  at_common_flutter: ^2.0.2
  at_contacts_flutter: ^3.0.2

  at_utils: ^3.0.0
#  at_client: ^2.0.3
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  at_backupkey_flutter: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeu
      fonts:
        - asset: assets/fonts/HelveticaLight.ttf
          weight: 300
        - asset: assets/fonts/HelveticaMedium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaRegular.ttf
          weight: 400
        - asset: assets/fonts/HelveticaBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaExtraBold.ttf
          weight: 800
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
